services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_gina_system
    # restart policy to make sure the container is restarted automatically when your machine is rebooted
    restart: unless-stopped
    ports:
      - "5431:5432"
    volumes:
      - ./.docker_volume/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gina_system
      POSTGRES_USER: adminadmin
      POSTGRES_PASSWORD: adminadmin
    networks:
      - dev_local

networks:
  dev_local:
    external: true
